### ISSUE TITLE
GeoIP Error

### ISSUE THREAD

**Issue by eren123danyel** [rsmusllp/king-phisher#430]
I have king phisher pre-installed with kali, this is my second time trying to use king phisher unsuccessfully on two different machines. Every time i try to run the server i get this exact error
```

INFO     the job manager has been started
INFO     adding new job with id: eaa8de50-f98e-4ace-b1ab-d2a780d6128f and callback function: _maintenance
INFO     adding new job with id: 20adaaad-e588-488b-b2b6-af2ecd5dd81c and callback function: ping_all
WARNING  the specified geoip database does not exist, downloading a new copy
ERROR    geoip database download failed (could not connect to the server)
CRITICAL server failed to build with error: could not download the geoip database
INFO     unloading 0 plugins
```

I have no idea what to do, and since this looks like a great tool, i'm a little disappointed.

**Comment by zeroSteiner** [comment]
This was fixed in version 1.16. Next time please fill out the issue template, it includes a spot for the version that you're running which I assume is 1.15.

You have to upgrade via git to 1.16.

**Comment by wolfthefallen** [comment]
I have submitted an issue to the Kali Bug Tracker to have them update to mirror the current master branch, as this is the second or third time this issue has poped up for Kali users.

**Comment by eren123danyel** [comment]
> This was fixed in version 1.16. Next time please fill out the issue template, it includes a spot for the version that you're running which I assume is 1.15.
> 
> You have to upgrade via git to 1.16.

Thank you,

After updating I have received a new error when running sudo ./install -u 

```
WARNING  no pre-existing pipenv environment was found, installing it now
pipenv encountered the following error:
Installing dependencies from Pipfile.lock (de6e07)…
Installing initially failed dependencies…
ERROR    failed to install the pipenv environment
```

**Comment by eren123danyel** [comment]
I have tried running the server as well, but that doesn't seem to resolve the issue it just throws back a similar error

**Comment by wolfthefallen** [comment]
try to force it to install the pip environment with `sudo ./KingPhisher --env-install` if that method fails use `export PIPENV_VENV_IN_PROJECT=True && pipenv --site-packages install`
